# Generated by Django 5.2.8 on 2026-04-13 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('letter_type', models.CharField(choices=[('joining', 'Joining Letter'), ('offer', 'Offer Letter'), ('definition', 'Definition Letter')], max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PassingYearOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FNAME', models.CharField(max_length=50)),
                ('LNAME', models.CharField(max_length=50)),
                ('BIRTHDAY', models.DateField(blank=True, null=True)),
                ('GENDER', models.CharField(blank=True, max_length=10)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONE', models.CharField(blank=True, max_length=10)),
                ('ADDRESS', models.CharField(blank=True, max_length=200)),
                ('CITY', models.CharField(blank=True, max_length=50)),
                ('COLLEGENAME', models.CharField(blank=True, max_length=100)),
                ('QUALIFICATION', models.CharField(blank=True, max_length=50, null=True)),
                ('BRANCH', models.CharField(blank=True, max_length=50)),
                ('PASSING_YEAR', models.CharField(blank=True, max_length=10)),
                ('TECHNOLOGY', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('visiting', 'Visiting'), ('adjoining', 'Adjoining'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='visiting', max_length=20)),
                ('visiting_at', models.DateTimeField(auto_now_add=True)),
                ('joining_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('fullstack', 'Full Stack')], max_length=50, null=True)),
                ('total_fees', models.IntegerField(blank=True, null=True)),
                ('paid_fees', models.IntegerField(default=0)),
                ('remaining_fees', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='appname.student')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('followup_date', models.DateField()),
                ('followup_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='appname.student')),
            ],
        ),
    ]
