# Generated by Django 6.0.4 on 2026-04-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('visiting', 'visiting'), ('adjoining', 'Adjoining'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='visiting', max_length=20),
        ),
    ]
